name: Default test pipeline

on:
  push:
    branches-ignore: [ master , main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: 'publish'

    # Reference your environment variables
    environment: cargo

    strategy:
      matrix:
        rust-channel: [ 'stable', 'nightly' ]
        rust-host: [ 'x86_64-unknown-linux-gnu', 'i686-unknown-linux-gnu' ]

    steps:
      - uses: actions/checkout@master
        with:
          # get git tags info
          fetch-depth: 0
      
      - name: Setup Rust
        with:
          rust-channel: ${{ matrix.rust-channel }}
          rust-host: ${{ matrix.rust-host }}
        uses: raftario/setup-rust-action@v1
      
      - name: Test package
        run: cargo test