name: Default test pipeline

on:
  workflow_dispatch:
  push:
    branches-ignore: [ main, master ]
    

jobs:
  build_and_test:
    name: Build and Test Rust Project
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && !github.event.pull_request

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: moonrepo/setup-rust@v1
        with:
          channel: '1.82.0'

      - name: Build the project
        run: cargo build --release

      - name: Run tests
        run: cargo test --verbose
