name: Default test pipeline

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest

    name: 'test'

    steps:
      - uses: actions/checkout@master
        with:
          # get git tags info
          fetch-depth: 0
      
      - uses: moonrepo/setup-rust@v1
        with:
          channel: '1.82.0'
      
      - name: Test package
        run: cargo test

      - name: Publish dry run
        run: cargo publish --dry-run